# Generated by Django 3.0.4 on 2020-06-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('xid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('xname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cname', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('schoolname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('adminid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('adminname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termname', models.CharField(max_length=100)),
            ],
        ),
    ]
