# Generated by Django 3.0.4 on 2020-06-14 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sysadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tname', models.CharField(max_length=100)),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='sysadmin.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxnum', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_course', to='sysadmin.Course')),
                ('termid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_course', to='sysadmin.Term')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_course', to='teacher.Teacher')),
                ('xid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_course', to='sysadmin.Campus')),
            ],
        ),
    ]
