# Generated by Django 2.2.11 on 2020-06-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200614_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercourse',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
