# Generated by Django 2.2.11 on 2020-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_offercourse_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offercourse',
            name='started',
        ),
        migrations.AddField(
            model_name='offercourse',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
