# Generated by Django 2.2.11 on 2020-06-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200614_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosecourse',
            name='kscore',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='choosecourse',
            name='pscore',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='choosecourse',
            name='zscore',
            field=models.FloatField(default=-1),
        ),
    ]
