# Generated by Django 2.2.11 on 2020-06-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_choosecourse_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choosecourse',
            name='started',
        ),
    ]
